<?php

namespace Tests\Feature;

use Tests\TestCase;
use App\Models\User;
use App\Models\Clientes;
use App\Models\InfraestructurasTiendas;
use App\Models\Suscripciones;
use App\Models\SuscripcionesCobros;
use App\Models\SuscripcionesPagos;
use App\Models\InfraestructurasPisos;
use App\Models\Infraestructuras;
use App\Filament\Pages\BalanceSuscripciones;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class BalanceSuscripcionesTest extends TestCase
{
    use DatabaseTransactions;

    protected User $adminUser;
    protected Clientes $client;
    protected InfraestructurasTiendas $shop;

    protected function setUp(): void
    {
        parent::setUp();

        // Run roles seeder
        $this->seed(\Database\Seeders\RolesAndPermissionsSeeder::class);

        // Create admin user
        $this->adminUser = User::factory()->create();
        $this->adminUser->assignRole('admin');

        // Create client
        $userClient = User::factory()->create([
            'nombres' => 'Milenka',
            'apellido_paterno' => 'Quiroga',
        ]);
        $userClient->assignRole('cliente');
        $this->client = Clientes::create([
            'user_id' => $userClient->id,
            'ci' => '7777777',
            'numero_celular' => '77777777',
            'genero' => 'femenino',
        ]);

        $infra = Infraestructuras::first() ?? Infraestructuras::create([
            'nombre' => 'Mall Central',
            'ubicacion' => 'La Paz',
            'pisos' => 1,
        ]);
        $piso = InfraestructurasPisos::create([
            'nombre' => 'Piso 1',
            'infraestructura_id' => $infra->id,
        ]);
        $this->shop = InfraestructurasTiendas::create([
            'numero' => 301,
            'nombre' => 'Nébula Coffee',
            'tamano' => '10x10',
            'id_estado' => 1,
            'infraestructura_piso_id' => $piso->id,
        ]);
    }

    public function test_cumulative_financial_audit_calculations(): void
    {
        $this->actingAs($this->adminUser);

        // 1. Create a 6-month contract with 7500 Bs total price (start 10 months ago, end 4 months ago)
        $sub1 = Suscripciones::create([
            'cliente_id' => $this->client->id,
            'infraestructuras_tienda_id' => $this->shop->id,
            'tipo' => '6 meses',
            'precio' => 7500.00,
            'fecha_inicio' => now()->subMonths(10)->toDateString(),
            'fecha_fin' => now()->subMonths(4)->toDateString(),
        ]);

        // 2. Create a 12-month contract with 15000 Bs total price (start 4 months ago, end 8 months from now)
        $sub2 = Suscripciones::create([
            'cliente_id' => $this->client->id,
            'infraestructuras_tienda_id' => $this->shop->id,
            'tipo' => '12 meses',
            'precio' => 15000.00,
            'fecha_inicio' => now()->subMonths(4)->toDateString(),
            'fecha_fin' => now()->addMonths(8)->toDateString(),
        ]);

        // Make sure cobros are generated by booted model hook
        $this->assertGreaterThan(0, $sub1->cobros()->count());
        $this->assertGreaterThan(0, $sub2->cobros()->count());

        $deudaSub1 = $sub1->cobros()->sum('monto');
        $deudaSub2 = $sub2->cobros()->sum('monto');
        $totalDeudaEsperada = $deudaSub1 + $deudaSub2;

        // 3. Simulate some payments
        // Let's pay all of sub1 cobros
        $cobros1 = $sub1->cobros;
        $totalPagadoSub1 = 0;
        foreach ($cobros1 as $cobro) {
            SuscripcionesPagos::create([
                'suscripcion_cobro_id' => $cobro->id,
                'monto_pagado' => $cobro->monto,
                'pago_pendiente' => 0,
                'fecha_pago' => now()->subMonths(5)->toDateString(),
                'metodo_pago' => 'efectivo',
                'estado_verificacion' => 'verificado',
            ]);
            $totalPagadoSub1 += $cobro->monto;
        }

        // Let's pay half of the first cobro of sub2
        $firstCobroSub2 = $sub2->cobros()->orderBy('fecha_vencimiento', 'asc')->first();
        SuscripcionesPagos::create([
            'suscripcion_cobro_id' => $firstCobroSub2->id,
            'monto_pagado' => $firstCobroSub2->monto / 2,
            'pago_pendiente' => $firstCobroSub2->monto / 2,
            'fecha_pago' => now()->subMonths(1)->toDateString(),
            'metodo_pago' => 'transferencia',
            'estado_verificacion' => 'verificado',
        ]);
        $totalPagadoSub2 = $firstCobroSub2->monto / 2;

        $totalPagadoEsperado = $totalPagadoSub1 + $totalPagadoSub2;
        $saldoRestanteEsperado = $totalDeudaEsperada - $totalPagadoEsperado;

        // Create an instance of the Filament page
        $pageInstance = new BalanceSuscripciones();
        $pageInstance->bootedInteractsWithTable();
        $tableConfig = $pageInstance->getTable();
        $columns = $tableConfig->getColumns();

        $montoAcumuladoCol = $columns['monto_acumulado_contratos'] ?? null;
        $pagadoCol = $columns['total_pagado'] ?? null;
        $saldoCol = $columns['saldo_pendiente'] ?? null;

        $this->assertNotNull($montoAcumuladoCol);
        $this->assertNotNull($pagadoCol);
        $this->assertNotNull($saldoCol);

        $montoAcumuladoValue = $montoAcumuladoCol->record($sub1)->getState();
        $pagadoValue = $pagadoCol->record($sub1)->getState();
        $saldoValue = $saldoCol->record($sub1)->getState();

        $this->assertEquals($totalDeudaEsperada, $montoAcumuladoValue);
        $this->assertEquals($totalPagadoEsperado, $pagadoValue);
        $this->assertEquals($saldoRestanteEsperado, $saldoValue);

        // Render the modal view and check contents
        $view = view('filament.components.reporte-cliente-modal', [
            'record' => $sub1,
            'deuda' => $totalDeudaEsperada,
            'pagado' => $totalPagadoEsperado,
        ]);

        $rendered = $view->render();

        // Check renamed tags
        $this->assertStringContainsString('Monto Total del Contrato', $rendered);
        $this->assertStringContainsString('Gráfica de Pagos', $rendered);
        $this->assertStringContainsString('Monto total cancelado', $rendered);

        // Check chronological payments and custom status labels
        $this->assertStringContainsString('Pago inicial', $rendered);
        $this->assertStringContainsString('Cobro Mensual #2 - Nébula Coffee', $rendered);
        $this->assertStringContainsString('PAGADO', $rendered);
        $this->assertStringContainsString('PAGO PARCIAL', $rendered);
        $this->assertStringContainsString('ATRASADO', $rendered);
        $this->assertStringContainsString('COBRO PROGRAMADO', $rendered);

        // Verify that the due date of an unpaid charge is shown as the payment date
        $secondCobroSub2 = $sub2->cobros()->orderBy('fecha_vencimiento', 'asc')->skip(1)->first();
        $expectedUnpaidDate = \Carbon\Carbon::parse($secondCobroSub2->fecha_vencimiento)->format('d/m/Y');
        $this->assertStringContainsString($expectedUnpaidDate, $rendered);
    }
}
